import streamlit as st
import folium
from streamlit_folium import st_folium

# ------------------------------------------------------------------------
# 1. PAGE CONFIGURATION & FELT.COM-STYLE CSS
# ------------------------------------------------------------------------
st.set_page_config(
    page_title="Felt-Style Map Viewer",
    page_icon="🗺️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS to force full-screen map, hide Streamlit chrome, and style the sidebar
st.markdown("""
    <style>
    /* Remove standard Streamlit padding and margins */
    .block-container {
        padding-top: 0rem !important;
        padding-bottom: 0rem !important;
        padding-left: 0rem !important;
        padding-right: 0rem !important;
        max-width: 100% !important;
    }
    
    /* Hide Header and Main Menu for a clean app-like feel */
    header { visibility: hidden; }
    #MainMenu { visibility: hidden; }
    footer { visibility: hidden; }
    
    /* Dark theme for sidebar */
    [data-testid="stSidebar"] {
        background-color: #111418;
        border-right: 1px solid #2d333b;
    }
    [data-testid="stSidebar"] * {
        color: #e6edf3;
    }
    
    /* Style radio buttons to look a bit cleaner */
    div.row-widget.stRadio > div {
        background: #1d2127;
        padding: 15px;
        border-radius: 8px;
        border: 1px solid #30363d;
    }
    </style>
""", unsafe_allow_html=True)


# ------------------------------------------------------------------------
# 2. SIDEBAR UI (TOOLBAR)
# ------------------------------------------------------------------------
st.sidebar.title("🗺️ Map Workspace")
st.sidebar.markdown("---")

st.sidebar.subheader("Basemap Configuration")

# Standard Basemaps including the new Custom Midnight Blue
basemaps = [
    "Carto DB Light",
    "Carto DB Dark",
    "Satellite",
    "OSM",
    "Midnight Blue"
]

selected_layer = st.sidebar.radio(
    "Select Basemap",
    options=basemaps,
    index=4 # Defaults to Midnight Blue
)

st.sidebar.markdown("---")
if selected_layer == "Midnight Blue":
    st.sidebar.success("Rendering custom Midnight Blue style.")
else:
    st.sidebar.info(f"Rendering standard {selected_layer} style.")

# ------------------------------------------------------------------------
# 3. MAP GENERATION LOGIC
# ------------------------------------------------------------------------

# Coordinates for Mandaluyong City, Metro Manila
MANDALUYONG_COORDS = [14.5794, 121.0359]

# Initialize base map without standard tiles
m = folium.Map(
    location=MANDALUYONG_COORDS, 
    zoom_start=14, # Slightly zoomed in to see the road details clearly
    tiles=None,
    control_scale=True,
    zoom_control=False # Hiding default controls for a cleaner Felt look
)

# Determine which tile set to apply
if selected_layer == "Carto DB Light":
    folium.TileLayer('CartoDB positron', name="Carto DB Light").add_to(m)

elif selected_layer == "Carto DB Dark":
    folium.TileLayer('CartoDB dark_matter', name="Carto DB Dark").add_to(m)

elif selected_layer == "OSM":
    folium.TileLayer('OpenStreetMap', name="OSM").add_to(m)

elif selected_layer == "Satellite":
    # Using Esri World Imagery for a clean, high-res satellite view
    folium.TileLayer(
        tiles='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
        attr='Esri World Imagery',
        name='Satellite'
    ).add_to(m)

elif selected_layer == "Midnight Blue":
    # -------------------------------------------------------------------------
    # ACTION REQUIRED: INSERT YOUR CUSTOM TILE URL BELOW
    # -------------------------------------------------------------------------
    # Replace the 'tiles' URL with the XYZ link generated by your map provider
    # (e.g., Mapbox, Stadia, JawgMaps) where you built the custom navy/gold style.
    
    custom_midnight_blue_url = 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png' # PLACEHOLDER
    
    folium.TileLayer(
        tiles=custom_midnight_blue_url,
        attr='Custom Midnight Blue Style',
        name='Midnight Blue',
        max_zoom=20
    ).add_to(m)

# ------------------------------------------------------------------------
# 4. RENDER MAP 
# ------------------------------------------------------------------------
st_folium(
    m, 
    use_container_width=True, 
    height=1000, 
    returned_objects=[] # Prevents Streamlit re-renders on map pan/zoom
)
